### PR TITLE
Port to Gtk3

### PR DESCRIPTION
**Pull request by tonadev**
### Explanation
This PR ports to Gtk3. 

### Reason
GTK+ 2 and GStreamer 0.10 are end of life.

### Test result
```
tonadev@TDPC:~/Documents/Work/OpenSource/code_in/sugarlabs/bichos2/bichos-activity$ sugar-activity

(sugar-activity:5552): Gtk-WARNING **: 21:55:19.290: Theme parsing error: gtk-widgets.css:16:32: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(sugar-activity:5552): Gtk-WARNING **: 21:55:19.291: Theme parsing error: gtk-widgets.css:17:35: The style property GtkExpander:expander-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version
Corriendo Intro . . .
Corriendo Canta Bichos . . .

(sugar-activity:5552): Gtk-WARNING **: 21:55:21.668: Attempting to add a widget with type CantaBichos+CantaBichos+Dialog to a SugarBichos+Bichos, but as a GtkBin subclass a SugarBichos+Bichos can only contain one widget at a time; it already contains a widget of type GtkVBox
Gtk-Message: 21:55:21.671: GtkDialog mapped without a transient parent. This is discouraged.

(sugar-activity:5552): Gtk-CRITICAL **: 21:55:47.535: gtk_widget_draw: assertion '!widget->priv->alloc_needed' failed


```
```
tonadev@TDPC:~/Documents/Work/OpenSource/code_in/sugarlabs/bichos2/bichos-activity$ sugar-activity

(sugar-activity:5520): Gtk-WARNING **: 21:53:47.699: Theme parsing error: gtk-widgets.css:16:32: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(sugar-activity:5520): Gtk-WARNING **: 21:53:47.699: Theme parsing error: gtk-widgets.css:17:35: The style property GtkExpander:expander-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version
Corriendo Intro . . .
Corriendo Canta Bichos . . .

(sugar-activity:5520): Gtk-WARNING **: 21:53:49.920: Attempting to add a widget with type CantaBichos+CantaBichos+Dialog to a SugarBichos+Bichos, but as a GtkBin subclass a SugarBichos+Bichos can only contain one widget at a time; it already contains a widget of type GtkVBox
Gtk-Message: 21:53:49.922: GtkDialog mapped without a transient parent. This is discouraged.

```
```
tonadev@TDPC:~/Documents/Work/OpenSource/code_in/sugarlabs/bichos2/bichos-activity$ sugar-activity

(sugar-activity:5533): Gtk-WARNING **: 21:54:10.521: Theme parsing error: gtk-widgets.css:16:32: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(sugar-activity:5533): Gtk-WARNING **: 21:54:10.522: Theme parsing error: gtk-widgets.css:17:35: The style property GtkExpander:expander-spacing is deprecated and shouldn't be used anymore. It will be removed in a future version
Corriendo Intro . . .
Corriendo Ojos Compuestos . . .

(sugar-activity:5533): Gtk-WARNING **: 21:54:13.376: Attempting to add a widget with type OjosCompuestos+OjosCompuestos+Dialog to a SugarBichos+Bichos, but as a GtkBin subclass a SugarBichos+Bichos can only contain one widget at a time; it already contains a widget of type GtkVBox
Gtk-Message: 21:54:13.397: GtkDialog mapped without a transient parent. This is discouraged.
```
### Observations (Not sure if port errors):
* When clicking CucaraSims, and then a button, it appears a 'dialog' and most of it is blank.
* Icon in sound button in CucaraSims doesn't appear until you click it and then it disappears again.
* When clicking "canciones" it zooms and doesn't stop.
*  __selecciones method seems not to work properly. (clicking an image does nothing)
* When clicking "imagenes" the column at the right blinks.

### CODE REVIEW

**Comment by pro-panda** [comment]
Thanks @tonadev. Great work.
Re the observations, please verify if they were present before your port.

**Comment by tonadev** [comment]
@pro-panda I can't. Its impossible to me to test it as I have no Gst 0.10 and it's no longer available for download.

**Comment by tonadev** [comment]
@chimosky 
> In CucaraSims/JAMediaImagenes/ImagePlayer.py you used
> self.xid = self.ventana.get_property('window').get_xid() but in Main.py you used
> xid = escenario.get_property('window').get_xid, please be consistent.
That's part of the original code, not mine.

**Comment by chimosky** [comment]
> That's part of the original code, not mine. Should I change it anyways?

The port is done by you, be consistent with the methods you use. `.get_xid` accesses the method and doesn't return anything, `get_xid()` does the opposite.

**Comment by tonadev** [comment]
Sorry @chimosky, I misunderstood your comment. I added the missing parentheses in the last commit. However the problems persists.

**Comment by pro-panda** [comment]
@tonadev Thanks

**Pull request merged**
