### PR TITLE
Port GObject based methods to GLib

### LINKED ISSUE #2: Port GObject to GLib

### PR DESCRIPTION
**Pull request by tonadev**
### Explanation
Fixes #2. This PR GObject based methods to GLib. 

### Reason
Thousands of PyGIDeprecationWarning occur in shell.log and activity logs when using PyGObject development releases, because of our use of GObject instead of GLib for certain methods.

### TODO
- [ ] Test (Couldn't because gtk isn't updated)

### CODE REVIEW

**Comment by tonadev** [comment]
Hi, I claimed this task but got unassigned by a mentor because gtk isn't updated. I can't claim it again because it says I abandoned the task. What should I do?

**Comment by chimosky** [comment]
@tonadev porting to gtk3 is very important as the activity working and the other ports depend on it, there's a task for porting this activity to gtk3, you can look for it if you want to.
You can close this PR, as a gtk3 port would also cover a port to GObject and Gstreamer.

**Comment by tonadev** [comment]
I already claimed it. So I need to update?:
* from: import gtk to: from gi.repository import Gtk
* from: import gobject to: from gi.repository import GObject
* from: import gst to: from gi.repository import Gst

**Comment by chimosky** [comment]
@tonadev yes.

**Pull request closed without merging**
