### PR TITLE
Port to Gtk3

### LINKED ISSUE #1: Port to GTK+ 3
Several deprecated components used;

-    GTK+ 2,
-    GStreamer 0.10

### PR DESCRIPTION
**Pull request by tonadev**
### Explanation
This PR fixes #1 by porting to Gtk3.

### Reason
GTK+ 2 and GStreamer 0.10 are end of life.

### TODO
- [ ] Test (Nothing is displayed and there is no error)

### CODE REVIEW

**Comment by chimosky** [comment]
Thanks @tonadev, reviewed to 65fde8c.

Few comments.
Use `Gdk.RGBA` instead of `Gdk.color_parse`, you can have a definition that looks like this in the activity file, maybe `CantaBichos.py`
```python
def colour_parse(colour):
    rgba = Gdk.RGBA()
    rgba.parse(colour)
    return rgba
```

You can use `Gdk.Display.get_default()` in place of `Gdk.display_get_default()`
Only one `gi.require_version` is needed for all imports so if you have more than one for a particular import, leave one in a particular file and remove instances of the rest.

Maintain naming convention of signal name and handler, you changed `expose-event` and you didn't change the signal handler in `Widgets.py`

**Comment by tonadev** [comment]
> Maintain naming convention of signal name and handler, you changed expose-event and you didn't 
> change the signal handler in Widgets.py
@chimosky What do you mean? Can you give an example?

**Comment by tonadev** [comment]
@chimosky PTAL at latest changes, I think it does all what you told me to do. However it still prints nothing.

**Comment by pro-panda** [comment]
@tonadev thanks, Reviewed.
Please confirm if the activity was running before your changes.
 - If yes, we can't merge this until we fix this PR
 - If no, open an issue for the same

**Comment by tonadev** [comment]
Before my changes I wasnt able to run sugar-activity because of import errors. And now there is sound but nothing is displayed.

**Pull request closed without merging**
